#!/usr/bin/env escript
%% This escript bootstraps libconf for your system.
%% Call it like so:
%%      ./bootstrap [command]
%% 
%% Where command is one of
%%  * install  - installs libconf and any dependent tools
%%  * generate - creates a configure.erl from a config file
%%  * build    - creates a binary escript (archive) from a configure.erl input
%%  * auto     - (the default) performs `install' followed by generate and/or
%%               build, depending on your config file
%% 

-define(CONFIG(K, C, D), (case lists:keymember(K, 1, C) of false -> D;
                                _ -> element(2, lists:keyfind(K, 1, C)) end)).
-define(CONFIG(K1, K2, C, D), ?CONFIG(K2, ?CONFIG(K1, C, []), D)).
-define(PATH(Parts), filename:join(Parts)).
-define(CWD, element(2, file:get_cwd())).

-record(project, {
    build_dir,
    deps_dir,
    temp_dir,
    config
}).

main(Args) ->
    case code:which(binary) of
        non_existing ->
            abort("libconf currently requires the use of the `binary' module!~n"
                  "you will need to run this escript with a release >= R14~n", []);
        _ ->
            execute(Args)
    end.

execute(["--help"]) ->
    {ok, Bin} = file:read_file(escript:script_name()),
    Lines = re:split(binary_to_list(Bin), "\n", [{return, list}]),
    Comments = string:join(lists:sublist(Lines, 2, 11), "~n"),
    io:format(re:replace(Comments, "%% ", "",
              [global, {return, list}]) ++ "~n"),
    halt(0);
execute(_) ->
    Proj = setup(load_config()),
    io:format("~p~n", [Proj]),
    ok.

setup(#project{
        build_dir=Base,
        deps_dir=Lib,
        temp_dir=Temp,
        config=Config }) ->
    [ mkdir(Path) || Path <- [Base, Lib, Temp] ],
    _Rebar = verify_rebar_install(?PATH([Temp, "rebar.zip"]), Config),
    ok.

mkdir(Path) ->
    io:format("Ensure ~s~n", [Path]),
    case filelib:ensure_dir(Path) of
        ok ->
            file:make_dir(Path);
        {error, eexist} ->
            file:make_dir(Path);
        Err ->
            Err
    end.

verify_rebar_install(Target, Config) ->
    case os:find_executable("rebar") of
        false ->
            install_rebar(Target, Config);
        Path ->
            Path
    end.

install_rebar(Target, Config) ->
    % we install the stock rebar for bootstrapping purposes
    Dest = ?PATH([filename:dirname(Target), "rebar"]),
    Exe = filename:join(Dest, "rebar"),
    case filelib:is_regular(Exe) of
        true ->
            Exe;
        false ->
            Url = "https://github.com/basho/rebar/zipball/master",
            case fetch(Url, Target, Config) of
                {error, Error} ->
                    abort("Unable to download rebar - ~p~n"
                          "please check your config/environment and try again~n",
                          [Error]);
                {ok, Target} ->
                    case zip:extract(Target, [memory]) of
                        {error, Reason} ->
                            abort("Unable to extract archive ~s: ~p~n",
                                  [Target, Reason]);
                        {ok, FileList} ->
                            [ file:write_file(rename(Path, Dest),
                                                Data, [write]) ||
                                                {Path, Data} <- FileList ],
                            case exec("./bootstrap", [{cd, Dest}]) of
                                {ok, _} ->
                                    Exe;
                                Err ->
                                abort("Unable to compile rebar: ~p~n", [Err])
                            end
                    end
            end
    end.

exec(Command, Env) ->
    PortSettings = [exit_status, {line, 16384}, stderr_to_stdout, hide],
    sh_loop(open_port({spawn, Command}, PortSettings ++ Env), []).

sh_loop(Port, Acc) ->
    receive
        {Port, {data, {eol, Line}}} ->
            sh_loop(Port, [Line ++ "\n" | Acc]);
        {Port, {data, {noeol, Line}}} ->
            sh_loop(Port, [Line | Acc]);
        {Port, {exit_status, 0}} ->
            {ok, lists:flatten(lists:reverse(Acc))};
        {Port, {exit_status, Rc}} ->
            {error, {Rc, lists:flatten(lists:reverse(Acc))}}
    end.

rename(Path, Dest) ->
    [_|P] = filename:split(Path),
    Target = filename:join(Dest, filename:join(P)),
    rebar_utils:ensure_dir(Target),
    Target.

abort(Msg, Args) ->
    io:format(Msg, Args), halt(1).

load_config() ->
    Bs = erl_eval:new_bindings(),
    case file:path_open([?CWD], "bootstrap.config", [read]) of
        {ok, Fd, _} ->
            try eval_stream(Fd, return, Bs) of
                {ok, C} ->
                    BuildDir = ?CONFIG(build_dir, C, ?CWD),
                    Default = ?PATH([BuildDir, "lib"]),
                    DepsDir = ?CONFIG(rebar_config, deps_dir, C, Default),
                    Temp = ?PATH([BuildDir, ".temp"]),
                    #project{ build_dir=BuildDir, deps_dir=DepsDir,
                              temp_dir=Temp, config=C };
                E1 ->
                    E1
            after
                file:close(Fd)
            end;
        {error, enoent} ->
            abort("bootstrap.config file not found!~n", []);
        E2 ->
            abort("Unable to load config: ~p~n", [E2])
    end.

ext_config_fn_handler(Func, Args) when is_function(Func) ->
    Func(Args);
ext_config_fn_handler({Mod, Func}, Args) ->
    apply(Mod, Func, Args).

eval_stream(Fd, Handling, Bs) ->
    eval_stream(Fd, Handling, 1, undefined, [], Bs).

eval_stream(Fd, H, Line, Last, E, Bs) ->
    eval_stream2(io:parse_erl_exprs(Fd, '', Line), Fd, H, Last, E, Bs).

eval_stream2({ok,Form,EndLine}, Fd, H, Last, E, Bs0) ->
    try erl_eval:exprs(Form, Bs0, none, {value, fun ext_config_fn_handler/2}) of
        {value, V, Bs} ->
            eval_stream(Fd, H, EndLine, {V}, E, Bs)
    catch Class:Reason ->
        Error = {EndLine, ?MODULE, {Class, Reason, erlang:get_stacktrace()}},
        eval_stream(Fd, H, EndLine, Last, [Error|E], Bs0)
    end;
eval_stream2({error,What,EndLine}, Fd, H, Last, E, Bs) ->
    eval_stream(Fd, H, EndLine, Last, [What | E], Bs);
eval_stream2({eof,EndLine}, _Fd, H, Last, E, _Bs) ->
    case {H, Last, E} of
        {return, {Val}, []} ->
            {ok, Val};
        {return, undefined, E} ->
            {error, hd(lists:reverse(E, [{EndLine,?MODULE,undefined_script}]))};
        {ignore, _, []} ->
            ok;
        {_, _, [_|_] = E} ->
            {error, hd(lists:reverse(E))}
    end.

fetch(Url, Target, C) ->
    case get({?MODULE, httpc}) of
        started ->
            ok;
        _ ->
            inets:start(),
            application:load(sasl),
            application:set_env(sasl, sasl_error_logger, false),
            lists:map(fun application:start/1, [sasl, crypto, public_key, ssl]),
            Timeout = ?CONFIG(remote_net_timeout, C, 6000),
            ProxyHost = ?CONFIG(remote_proxy_host, C, undefined),
            case ProxyHost of
                undefined ->
                    httpc:set_options([{timeout, Timeout},
                                       {connect_timeout, Timeout}]);
                Host ->
                    Port = ?CONFIG(remote_proxy_port, C, "8080"),
                    httpc:set_options([{proxy, {{Host, Port}, ["localhost"]}},
                                       {timeout, Timeout},
                                       {connect_timeout, Timeout}])
            end,
            put({?MODULE, httpc}, started)
    end,
    rebar_utils:ensure_dir(Target),
    Request = {Url, [{"User-Agent", "Erlang-Rebar"}]},
    rebar_log:log(debug, "Attempting to fetch ~s into ~s~n", [Url, Target]),
    case httpc:request(get, Request, [{relaxed, true}],
                                     [{stream, Target}, {full_result, true}]) of
        {ok, saved_to_file} ->
            rebar_log:log(debug, "Successfully fetched tag...~n", []),
            {ok, Target};
        {ok, {{_, 404, _}, _, _}} ->
            rebar_log:log(warn, "~s not found!~n", [Url]),
            {error, missing};
        Error ->
            rebar_log:log(warn, "Error trying to load remote: ~p~n", [Error]),
            {error, Error}
    end.

